[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
bincode = "1.3.3"
brotli = "3.3.3"
serde = "1.0.136"
tantivy = { version = "0.16.1", default-features = false }
thiserror = "1.0.30"
shared_derive = { path = "../shared_derive" }
