name: Create and Pack
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout OnyxBay
        uses: actions/checkout@v2
        with:
          repository: ChaoticOnyx/OnyxBay
          ref: dev
          path: ./OnyxBay
      - name: Check for changes
        shell: pwsh
        env:
          REF: dev
          TARGET_REPOSITORY: ./OnyxBay
        run: ./check_changes.ps1
      - name: Run Packer
        shell: pwsh
        env:
          TARGET_REPOSITORY: ./OnyxBay
        run: ./pack.ps1
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          add: '["*.bin", "*.txt"]'
